model:
  svid: 
    target: WSBSR.model.svid.SVID
    params:
      num_classes: 25 # number of image level labels
      grid_size: 4 # number of regions = n * n

  cldm:
    target: WSBSR.model.cldm.ControlLDM
    params:
      latent_scale_factor: 0.18215
      unet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False
      vae_cfg:
        embed_dim: 4
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
      clip_cfg:
        embed_dim: 1024
        vision_cfg:
          image_size: 224
          layers: 32
          width: 1280
          head_width: 80
          patch_size: 14
        text_cfg:
          context_length: 77
          vocab_size: 49408
          width: 1024
          heads: 16
          layers: 24
        layer: "penultimate"
      controlnet_cfg:
        use_checkpoint: True
        image_size: 32 # unused
        in_channels: 4
        hint_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_head_channels: 64 # need to fix for flash-attn
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 1024
        legacy: False

  diffusion:
    target: WSBSR.model.gaussian_diffusion.Diffusion
    params:
      linear_start: 0.00085
      linear_end: 0.0120
      timesteps: 1000
      zero_snr: True
      parameterization: v



train:
  # pretrained IRControlNet path
  IRC_ckpt: ./WSBSR/weights/IRControNEt/DiffBIR_v2.1.pt
  # pretrained cldm path
  cldm_ckpt: ./WSBSR/weights/cldm/sd2.1-base-zsnr-laionaes5.ckpt
  # pretrained SVID path
  svid_ckpt: 
  # exp path
  exp_dir: ./WSBSR/experiments/train/exp2
  train_steps: 300000
  log_every: 10
  ckpt_every: 10000
  val_every: 100
  batch_size: 4
  learning_rate: 1e-4
  momentum: 0.9
  lambda_reg: 1e-4
  lambda_w: 1.0  # SVID lambda
  lambda_c: 10.0  # Cycle lambda
  warmup_epochs: 5
  num_workers: 4
  noise_aug_timestep: 200
  upscale: 4


dataset:
  train:
    target: WSBSR.dataset.WSDataset.WSDataset
    params:
      dataset_dir : ./WSBSR/data/1
      output_size : 512
      crop_type : "center"
      blur_kernel_size : 41
      kernel_list : ['iso']
      kernel_prob : [0.5]
      blur_sigma : [0.8, 3.2]
      downsample_range : [2, 4]
      valid_extensions : [".png", ".jpg", ".jpeg"]
      n_regions : 4
      sigma_step : 0.1

