dataset:
  train:
    target: dataset.OODDataset.OOD_Dataset
    params:
      dataset_dir : 
      out_size : 512
      crop_type : "center"
      blur_kernel_size : 41
      kernel_list : ['iso']
      kernel_prob : [0.5]
      blur_sigma : [0.8, 3.2]
      downsample_range : [2, 4]
      valid_extensions : [".png", ".jpg", ".jpeg"]
      n_regions : 4